import './style.css'

type View='Overview'|'Console'|'Files'|'Logs'|'Services'|'Guide'
let view:View='Overview',language:'es'|'en'='es',authenticated=false,connecting=false,notice=''
const repo='https://github.com/pablo2611/serverdock'
const t=(es:string,en:string)=>language==='es'?es:en
const labels:Record<View,[string,string]>={Overview:['General','Overview'],Console:['Consola','Console'],Files:['Archivos','Files'],Logs:['Registros','Logs'],Services:['Servicios','Services'],Guide:['Guía','Guide']}
const nav=()=>(Object.keys(labels) as View[]).map(v=>`<button class="nav-item ${view===v?'active':''}" data-view="${v}">${t(...labels[v])}</button>`).join('')
const login=()=>`<main class="login-page"><section class="login-card"><a class="brand" href="#">Server<span>Dock</span></a><div class="eyebrow">${t('ACCESO PRIVADO','PRIVATE ACCESS')}</div><h1>${t('Administración segura de tu VPS','Secure VPS administration')}</h1><p>${t('Inicia sesión para acceder a tu panel personal.','Sign in to access your personal control panel.')}</p><form id="login-form"><label>${t('Usuario','Username')}<input name="username" required autocomplete="username" value="pablo"></label><label>${t('Contraseña','Password')}<input name="password" required type="password" autocomplete="current-password"></label><button class="button">${t('Entrar a ServerDock','Sign in to ServerDock')}</button><small id="login-error"></small></form><a class="project-login" href="${repo}" target="_blank" rel="noreferrer">${t('Proyecto en GitHub','Project on GitHub')}</a></section></main>`
const empty=(title:string,copy:string)=>`<section class="content-card"><div class="section-head"><div><div class="eyebrow">${t('CONECTADO AL BACKEND','BACKEND CONNECTION')}</div><h2>${title}</h2></div></div><div class="empty"><b>${copy}</b><p>${t('Los datos aparecerán únicamente cuando el agente privado esté instalado en tu VPS.','Data will appear only when the private agent is installed on your VPS.')}</p><button class="button" data-connect>${t('Instalar y conectar mi VPS','Install and connect my VPS')}</button></div></section>`
const overview=()=>`<section class="welcome"><div><div class="eyebrow">${t('UN VPS · UN PANEL PRIVADO','ONE VPS · ONE PRIVATE PANEL')}</div><h2>${t('Controla tu bot desde ServerDock.','Manage your bot from ServerDock.')}</h2><p>${t('Conecta tu servidor Kamatera una sola vez. El agente queda en tu VPS y el panel solo estará disponible con tu sesión.','Connect your Kamatera server once. The agent stays on your VPS and the panel is available only with your session.')}</p><div class="welcome-actions"><button class="button" data-connect>${t('Instalar y conectar mi VPS','Install and connect my VPS')}</button><button class="button secondary" data-view="Guide">${t('Cómo funciona','How it works')}</button></div></div><div class="setup-panel"><span class="step-number">01</span><b>${t('Instalación segura','Secure installation')}</b><p>${t('Introduce tu IP y acceso SSH. Se usan solo para instalar el agente privado.','Enter your IP and SSH access. They are used only to install the private agent.')}</p><span class="step-number">02</span><b>${t('Gestiona tu bot','Manage your bot')}</b><p>${t('Después tendrás consola, archivos, registros y controles de servicio.','Afterwards you will have console, files, logs and service controls.')}</p></div></section>`
const guide=()=>`<section class="content-card guide"><div class="eyebrow">${t('CÓMO FUNCIONA','HOW IT WORKS')}</div><h2>${t('Conexión de un solo VPS','Single VPS connection')}</h2><ol><li><b>${t('Inicia sesión.','Sign in.')}</b><span>${t('El panel es privado y requiere tu contraseña.','The panel is private and requires your password.')}</span></li><li><b>${t('Añade el acceso SSH.','Add SSH access.')}</b><span>${t('Indica la IP, el usuario y una clave privada SSH.','Provide the IP, user and an SSH private key.')}</span></li><li><b>${t('Instalación automática.','Automatic installation.')}</b><span>${t('El instalador crea el agente de ServerDock en tu VPS.','The installer creates the ServerDock agent on your VPS.')}</span></li><li><b>${t('Control privado.','Private control.')}</b><span>${t('Los archivos y comandos se ejecutan en tu VPS, no en Vercel.','Files and commands run on your VPS, not on Vercel.')}</span></li></ol></section>`
const connect=()=>!connecting?'':`<div class="modal" role="dialog" aria-modal="true"><form id="connect-form"><button type="button" class="close" data-close>×</button><div class="eyebrow">${t('INSTALAR AGENTE','INSTALL AGENT')}</div><h2>${t('Conecta tu VPS','Connect your VPS')}</h2><p class="muted">${t('El instalador usará estos datos una sola vez para preparar tu agente privado.','The installer will use these details once to prepare your private agent.')}</p><label>${t('IP del VPS','VPS IP')}<input name="host" required value="83.229.3.17"></label><div class="form-grid"><label>${t('Usuario SSH','SSH user')}<input name="username" required value="root"></label><label>${t('Puerto','Port')}<input name="port" required value="22"></label></div><label>${t('Clave privada SSH','SSH private key')}<textarea name="privateKey" required placeholder="-----BEGIN OPENSSH PRIVATE KEY-----"></textarea></label><button class="button">${t('Instalar y conectar','Install and connect')}</button><p class="form-note">${t('Nunca uses la contraseña de tu panel como clave SSH.','Never use your panel password as an SSH key.')}</p></form></div>`
function screen(){return view==='Guide'?guide():view==='Overview'?overview():empty(t(...labels[view]),t('Aún no hay datos reales disponibles.','No real data is available yet.'))}
function render(){document.title=language==='es'?'ServerDock | Control de VPS':'ServerDock | VPS Control';if(!authenticated){document.querySelector<HTMLDivElement>('#app')!.innerHTML=login();document.querySelector<HTMLFormElement>('#login-form')!.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});if(r.ok){authenticated=true;render()}else document.querySelector('#login-error')!.textContent=t('Usuario o contraseña incorrectos.','Incorrect username or password.')};return}document.querySelector<HTMLDivElement>('#app')!.innerHTML=`<main><aside><a class="brand" href="#">Server<span>Dock</span></a><div class="project"><img src="https://github.githubassets.com/favicons/favicon-dark.svg" width="18" height="18" alt=""><a href="${repo}" target="_blank" rel="noreferrer">${t('Proyecto en GitHub','Project on GitHub')}</a></div><nav>${nav()}</nav><button class="logout" data-logout>${t('Cerrar sesión','Sign out')}</button></aside><section class="page"><header class="topbar"><div><div class="eyebrow">${t('CENTRO DE CONTROL','CONTROL CENTER')}</div><h1>${t(...labels[view])}</h1></div><div class="top-actions"><button class="language" data-language>${language==='es'?'EN':'ES'}</button><button class="button" data-connect>${t('Conectar VPS','Connect VPS')}</button></div></header>${notice?`<div class="notice">${notice}</div>`:''}${screen()}<footer>ServerDock · ${t('Administración privada de VPS','Private VPS administration')}</footer></section></main>${connect()}`;document.querySelectorAll<HTMLElement>('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view as View;render()});document.querySelectorAll<HTMLElement>('[data-language]').forEach(b=>b.onclick=()=>{language=language==='es'?'en':'es';render()});document.querySelectorAll<HTMLElement>('[data-connect]').forEach(b=>b.onclick=()=>{connecting=true;render()});document.querySelectorAll<HTMLElement>('[data-close]').forEach(b=>b.onclick=()=>{connecting=false;render()});document.querySelector<HTMLElement>('[data-logout]')!.onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});authenticated=false;render()};document.querySelector<HTMLFormElement>('#connect-form')?.addEventListener('submit',e=>{e.preventDefault();notice=t('El instalador automático se añadirá tras terminar la configuración segura.','The automatic installer will be added after secure configuration is complete.');connecting=false;render()})}
fetch('/api/auth/session').then(r=>{authenticated=r.ok;render()}).catch(()=>render())
